### ISSUE TITLE
The Email Retrieve, Compose & Send Routes

### ISSUE THREAD

**Issue by is-it-ayush** [MultiEmail/MultiEmail-backend#122]
### Description

These are the requested features (routes):
- `/mail/retrieve/:service/:amt`  (GET) : Fetched the `amt` number of last emails from the `service`. If amt is not provided. The default `amt` would be 100.
- `/mail/drafts/:service`  (GET) : Returns all the draft emails, their associated id's with their associated service.
> Note: If the service is not provided, it returns all draft mails and their associated id's.
- `/mail/edit/:id` (PATCH) : Updates the content of the given email that has the following `id`
- `/mail/drafts` (POST) : Saves a draft email by giving it an id and saves the service with it.
- `/mail/send/:id` (GET) : Sends the mail that has the `id` if it exists. Every saved draft email with have a id and a service saved.

Here the service could be any mail service that has a Public API and work's via a token. Some considerations: GMail, Hotmail, Yahoo Mail, Etc.

### Anything else?

Feel free to add any other routes that you might think would be necessary.

**Comment by aayushchugh** [comment]
Will work on this issue in sub issues
