### ISSUE TITLE
[FEAT] :sparkles: Admin should be able to view all sent marketing emails

### ISSUE THREAD

**Issue by aayushchugh** [MultiEmail/MultiEmail-backend#142]
### Description

create new route `GET /admin/marketing-emails` by which admin will be able to view all the sent marketing emails

### Anything else?

write logic in `marketingEmail.controller.ts`

**Comment by tharun634** [comment]
I can work on this once #144 is merged

**Comment by JaimeHidalgo** [comment]
Do you need help?

**Comment by aayushchugh** [comment]
@JaimeHidalgo yes
