### ISSUE TITLE
[FEAT] :sparkles: get all users which who have added option to receive marketing emails

### ISSUE THREAD

**Issue by aayushchugh** [MultiEmail/MultiEmail-backend#158]
### Description

add new query to fetch all users route `receiveMarketingEmails`.
if this is true than only fetch users in which `receiveMarketingEmails` is set to `true`

example:- `GET /api/admin/users?receiveMarketingEmails=true`

### Anything else?

start working on this only when #157 is closed

**Comment by Arbaz23** [comment]
hello, @aayushchugh Can you please assign this to me?

**Comment by shikhar13012001** [comment]
Hi @aayushchugh  I would like to work on this issue, Can you please assign this to me?

**Comment by Arbaz23** [comment]
@aayushchugh  Can you please assign this to me?

**Comment by aayushchugh** [comment]
@shikhar13012001 sure you can work on this one after #157 is closed

**Comment by aayushchugh** [comment]
@shikhar13012001 You can start working on this now
