### ISSUE TITLE
[FEAT] :sparkles: create new route to unsubscribe from marketing emails

### ISSUE THREAD

**Issue by aayushchugh** [MultiEmail/MultiEmail-backend#159]
### Description

create new route `GET /api/users/:id/marketing-emails/unsubscribe` by which user will not receive marketing emails any more

we can set user's `recieveMarketingEmails` option to `false` in database to unsubscribe from marketing emails

**Comment by Arbaz23** [comment]
hello, can i take this ?

**Comment by Arbaz23** [comment]
@aayushchugh can you assign this to me please

**Comment by aayushchugh** [comment]
Sure @Arbaz23

**Comment by Arbaz23** [comment]
thks, @aayushchugh i work on it

**Comment by aayushchugh** [comment]
@Arbaz23 are you working on this?
