### ISSUE TITLE
[REFACTOR] :recycle: rename `admin.controller.ts` to `user.controller.ts`

### ISSUE THREAD

**Issue by aayushchugh** [MultiEmail/MultiEmail-backend#160]
### Description

in `admin.controller.ts` there is code related to users so we can rename it to improve code quality and maintain code standards

**Comment by YashJain2409** [comment]
Can i work on this?

**Comment by aayushchugh** [comment]
@YashJain2409 Yes you can work on this but remember that main branch is updated so you can't just rename to file
but you have to move the content of `admin.controller.ts` to `user.controller.ts` (which is already existed) and update the
imports accordingly

**Comment by YashJain2409** [comment]
i have created pull request,you can review it
