### ISSUE TITLE
Add All contributors bot for github

### ISSUE THREAD

**Issue by aayushchugh** [MultiEmail/MultiEmail-backend#17]
### Description

add all contributor's bot so that every developer gets the necessary credits

### Anything else?

https://allcontributors.org/docs/en/bot/installation

**Comment by codewithnadeem14502** [comment]
hello sir, I would love to work on this issue, I am new to open source so it will be a good start for me. if you give hints/little help then i will assure you  i will complete the task  , thank you

**Comment by aayushchugh** [comment]
@codewithnadeem14502 Thanks for showing the interest, you can join our [discord](https://discord.gg/asZUEYDt) server for further assistance

there will be many contributors in this project so adding them manually in readme will be frustrating, so I thought of adding
[All Contributors](https://allcontributors.org/en) bot which will help automate this task

let me know when you are ready and I will assign you this issue

and no need to call me `sir` I am younger than you

**Comment by shivamvishwakarm** [comment]
Hey aayush, I want to work on this issue. Please assign it to me.

**Comment by aayushchugh** [comment]
@shivamvishwakarm sure

**Comment by shivamvishwakarm** [comment]
@aayushchugh  please also label this with HACKTOBERFEST-ACCEPTED

**Comment by aayushchugh** [comment]
@shivamvishwakarm done
