### ISSUE TITLE
[FEAT] :sparkles: Create admin user from command line

### ISSUE THREAD

**Issue by aayushchugh** [MultiEmail/MultiEmail-backend#21]
### Description

We can't create a rest api endpoint for creating admin user because if we do than anyone can use that endpoint to create
admin user for them

We should implement a command that will run in terminal which will create a new user in database with role admin

example command:-

```bash
admin -e <email> -p <password>
```

### Anything else?

I have already implemented this in another project you can get reference of code from here:-
https://github.com/shriproperty/server/blob/dev/bin/index.ts
https://github.com/shriproperty/server/blob/dev/package.json#L12-L14

**Comment by BitOfAByte** [comment]
Completed
