### ISSUE TITLE
[FEAT] :sparkles: Username should not contain any spaces or capital letters

### ISSUE THREAD

**Issue by aayushchugh** [MultiEmail/MultiEmail-backend#22]
### Description

When user will signup than the username should not contain any of these things

- Capital letters
- Numbers
- special characters
- spaces

**Comment by tharun634** [comment]
Hey, can I work on this issue?

I can directly add String Validation over here, right?
https://github.com/MultiEmail/MultiEmail-backend/blob/7e3f36609cbdfd82ffda074860e20dbd602083ce/src/controllers/auth.controller.ts#L16

**Comment by is-it-ayush** [comment]
@tharun634 Thank You for showing Interest. Go Ahead! You can do so. I'm assigning you to this issue. Create a PR with the template and the changes. You can join our [discord](https://discord.com/invite/asZUEYDt) to be a part too. Good Luck!

**Comment by aayushchugh** [comment]
@is-it-ayush can we implement this using REGEX?

**Comment by is-it-ayush** [comment]
Yes @aayushchugh, I think we use inbuilt functions and regex. Something like a two-way check would be nice both on frontend and backend for double verification i.e. before the form data is sent and after the data is recieved on the frontend. ```[ `!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?~ ]``` would work. I checked it up on [Regxr](https://regexr.com/). Before Regex Validation, we can convert the string intro lowercase and trim it. This would fix it.
