### ISSUE TITLE
Create issue template for no template

### ISSUE THREAD

**Issue by aayushchugh** [MultiEmail/MultiEmail-backend#23]
### Description

If we create a new issue than we have to follow a template but if any issue don't satisfy the template than there should be
a template which will not contain any pre defined headings, labels, etc..

eg:- if we create a issue `Configure Eslint` than it will not fall into any category i.e.
- Enhancement
- Refactor
- Bug
- Security
- Docs

so there should be a template which will be empty so that user can write whatever they want

**Comment by tharun634** [comment]
Hello, can I take this issue up?

I will be creating a `config.yml` for ISSUES_TEMPLATE with `blank_issues_enabled` option

**Comment by aayushchugh** [comment]
@tharun634 sure you can work on this
