### ISSUE TITLE
[FEAT] :sparkles: implement deserializeUser middleware

### ISSUE THREAD

**Issue by aayushchugh** [MultiEmail/MultiEmail-backend#3]
### Description

this middleware will get user from session or cookie and then save it to `res.local.user`

### Anything else?

file:- `/src/middleware/deserializeUser.middleware.ts`

reference from another project:- https://github.com/shriproperty/server/blob/dev/src/middlewares/deserializeUser.middleware.ts

**Comment by DaatUserName** [comment]
ok
