### ISSUE TITLE
[DOCS] :memo: Configure TSdoc for generating documentation

### ISSUE THREAD

**Issue by aayushchugh** [MultiEmail/MultiEmail-backend#34]
### Description

We should configure TSdoc for generating documentation for our utility functions

### Anything else?

https://tsdoc.org/

**Comment by shivamvishwakarm** [comment]
@aayushchugh  I want to do this work.

**Comment by aayushchugh** [comment]
go ahead @shivamvishwakarm

you can also message in discord server so that if I am not available someone else will
assign you the issue

**Comment by shivamvishwakarm** [comment]
ok

**Comment by aayushchugh** [comment]
@shivamvishwakarm The main task is that we need to create a new script in package.json and when we run it
it should generate documentation for all the functions

**Comment by shivamvishwakarm** [comment]
can we close this issue?

**Comment by aayushchugh** [comment]
@shivamvishwakarm yup forgot to do that
