### ISSUE TITLE
Configure eslint

### ISSUE THREAD

**Issue by aayushchugh** [MultiEmail/MultiEmail-backend#4]

**Comment by DaatUserName** [comment]
nicer

**Comment by DaatUserName** [comment]
k

**Comment by shivamvishwakarm** [comment]
Hey aayush, I also wanted to work on this issue. Please assign

**Comment by aayushchugh** [comment]
@shivamvishwakarm assigned you this issue and if you want to code for this project
 than you can join us on [Discord](https://discord.gg/asZUEYDt) server

**Comment by shivamvishwakarm** [comment]
Discord link is invalid

**Comment by aayushchugh** [comment]
Here is new one 
https://discord.gg/kFJGJANZ
