### ISSUE TITLE
[FEAT] :sparkles: Implement middleware to protect admin routes

### ISSUE THREAD

**Issue by aayushchugh** [MultiEmail/MultiEmail-backend#49]
### Description

Implement a middleware that will protect routes which only admin can access

### Anything else?

get current user by using -> `res.locals.user`
and check if user role is `admin` than use `next()` function otherwise return `403` status code

**Comment by drishit96** [comment]
Hi @aayushchugh, I'd like to work on this

**Comment by aayushchugh** [comment]
@drishit96 go ahead I am assigning you this issue

You can join our [discrod](https://discord.com/invite/gkvCYzRKEB) to be part of our community

**Comment by drishit96** [comment]
@aayushchugh Are there any existing routes that require admin role? I have created the middleware, just wanted to use it in those routes.

**Comment by aayushchugh** [comment]
@drishit96 there aren't any at this point
