### ISSUE TITLE
Should we setup Docker?

### ISSUE THREAD

**Issue by aayushchugh** [MultiEmail/MultiEmail-backend#62]
@is-it-ayush @DaatUserName @MultiEmail/backend-developers  Should we setup Docker for the backend?

**Comment by is-it-ayush** [comment]
Yes, it'd be good to use Docker. 👍🏼

**Comment by Karol-Ari** [comment]
Yes

**Comment by shivamvishwakarm** [comment]
Yes, It's nice to add docker in our project.

**Comment by BitOfAByte** [comment]
sure

**Comment by KanLSK** [comment]
Yes
