### ISSUE TITLE
[FEAT] :sparkles: Setup Docker

### ISSUE THREAD

**Issue by aayushchugh** [MultiEmail/MultiEmail-backend#63]
### Description

We will configure Docker as decided in issue #62 

### Anything else?

reference: - https://www.docker.com/

**Comment by rexdivakar** [comment]
Hey @aayushchugh i can add work on ths

**Comment by aayushchugh** [comment]
@rexdivakar I am currently working on this one but you can join our [Discord Server](https://discord.com/invite/gkvCYzRKEB) to watch for something else
