### ISSUE TITLE
[SECURITY] :lock: Add rate limiter to prevent attacks like slowloris

### ISSUE THREAD

**Issue by developer-diganta** [MultiEmail/MultiEmail-backend#65]
### Description

Add rate limiter to ensure that too many requests from an ip (open) are not made to avoid crashing of server

### How can we solve this

A rate limiter for express can be added

### Anything else?

If this seems legit, can I work on it?

**Comment by aayushchugh** [comment]
@developer-diganta thanks for raising this issue, we will review it and work on this one

**Comment by aayushchugh** [comment]
@is-it-ayush @DaatUserName  Can you take look into this issue
and should we work on this one?

**Comment by BitOfAByte** [comment]
> @is-it-ayush @DaatUserName Can you take look into this issue and should we work on this one?

I'm down... I like the idea

**Comment by BitOfAByte** [comment]
> ### Description
> Add rate limiter to ensure that too many requests from an ip (open) are not made to avoid crashing of server
> 
> ### How can we solve this
> A rate limiter for express can be added
> 
> ### Anything else?
> If this seems legit, can I work on it?

You can work on it if you want to

**Comment by developer-diganta** [comment]
I'll work on it!

**Comment by aayushchugh** [comment]
@developer-diganta are you working on this?

**Comment by developer-diganta** [comment]
Yep... will make the pr soon
