### ISSUE TITLE
[DOCS] : Link License and Contributing.md to ReadMe

### ISSUE THREAD

**Issue by shashankbhatgs** [MultiEmail/MultiEmail-backend#74]
### Description

**Is your feature request related to a problem? Please describe.**

Improving the docs by adding the LICENSE and contributing.md links to the ReadMe file.

**Describe the solution you'd like**

I would like to add the links of LICENSE and Contributing.md at the bottom of the readme file so as to make the readme more structured.

**Comment by aayushchugh** [comment]
@shashankbhatgs go ahead I have assigned you the issue
