### ISSUE TITLE
[DOCS] :memo: Remove empty `Acknowledgements` section from `README.md`

### ISSUE THREAD

**Issue by aayushchugh** [MultiEmail/MultiEmail-backend#79]
### Description

There is empty `Acknowledgements` section present in `README.md` file we need to remove that

### Anything else?

![image](https://user-images.githubusercontent.com/69336518/193838595-864d5fbd-c371-416b-a1f7-59da8afa6024.png)

**Comment by MufaddalHakim** [comment]
working on it

**Comment by Madhvik007** [comment]
Hi, I can help you with this

**Comment by aayushchugh** [comment]
completed in #80
