### ISSUE TITLE
[BUG] :bug: Emails should not be send in `test` environment

### ISSUE THREAD

**Issue by aayushchugh** [MultiEmail/MultiEmail-backend#89]
### Current Behaviour

When we run `yarn test` command nodemailer send a email

### Expected Behaviour

`nodemailer` should not send emails in `test` environment

### Steps To Reproduce

1. use `yarn test` command

### Anything else?

We can add new if condition in `email.util.ts` at `sendEmail` function that will just `return` if current node environment is
`test`

**Comment by kmartin62** [comment]
> We can add new if condition in email.util.ts at sendEmail function that will just return if current node environment is
test

Isn't this already done? `	if (process.env.NODE_ENV === "test") return;` https://github.com/MultiEmail/backend/blob/6448b5aba002378f470a20699e25f6f6c2abf79a/src/utils/email.util.ts#L35

**Comment by aayushchugh** [comment]
oops I didn't see that

**Comment by kmartin62** [comment]
If the test still passes, you might check whether the env name is really `test` or not :) Or the test might be broken, didn't check it out from my side.

**Comment by kmartin62** [comment]
Also, I think that you should isolate the env names in a separate file, have them stacked there and import them whenever you need. If by any chances you change the name of the environment then through all the whole app you'd need to do the same change. Having it in one file will require to change it only there.

**Comment by aayushchugh** [comment]
nice suggestion
