### ISSUE TITLE
[REFACTOR] :recycle: Seprate admin action's in it's own endpoint.

### ISSUE THREAD

**Issue by is-it-ayush** [MultiEmail/MultiEmail-backend#90]
### Description

Refactor the code to differentiate between /admin and /user's endpoints. All performable API calls for admin can have thier own endpoint for better security and management. It would also avoid the confusion for future Developer's.

### Current Behaviour (as of currently available endpoint's):
- [ ] /users/markverified/:id  (PATCH) - Marks a user verified.
- [ ] /users/:id (DELETE)  - Delete's a user.

### Expected Behaviour
- [ ] /admin/users/markverified/:id  (PATCH) - Marks a user verified.
- [ ] /admin/users/:id (DELETE)  - Delete's a user.
. . .

**Comment by aayushchugh** [comment]
>/users/:id (PATCH) - Updates a user

@is-it-ayush I have created this route so that user can update his username so shouldn't
it be as `PATCH /users/:id`

**Comment by is-it-ayush** [comment]
@aayushchugh . Thank You! I updated the original issue.
