### ISSUE TITLE
[FEAT] :sparkles: Setup GitHub actions to run tests on every PR

### ISSUE THREAD

**Issue by aayushchugh** [MultiEmail/MultiEmail-backend#95]
### Description

we need to run tests on backend on every PR

**Comment by alberturria** [comment]
Hi @aayushchugh could I pick up this this issue and work on it? 🙂

**Comment by aayushchugh** [comment]
@alberturria Go ahead, you can also join our [discord server](https://discord.gg/gkvCYzRKEB) if you need any help
