### ISSUE TITLE
[SECURITY] :lock: A user can update other user's username.

### ISSUE THREAD

**Issue by is-it-ayush** [MultiEmail/MultiEmail-backend#96]
### Description

User's can update other user's username provided they have the Database Id through `/users/:id` route.

**Comment by aayushchugh** [comment]
@is-it-ayush if you can implement a re-useable middleware that validate that if user is same user, that will be great

**Comment by is-it-ayush** [comment]
It's not required on other route's. This was a special case here. However I can add it if you want.

**Comment by aayushchugh** [comment]
@is-it-ayush reusable middleware is good because we might need it in future

**Comment by is-it-ayush** [comment]
Resolved via #97
